# Generated by Django 2.1.7 on 2019-06-10 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='media/files/')),
            ],
        ),
        migrations.CreateModel(
            name='SharePlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='shareplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shr_io.SharePlace'),
        ),
    ]
